### ISSUE TITLE
logo in a vector format

### ISSUE THREAD

**Issue by gilbarbara** [tastejs/tastejs.github.com#4] opened 2015-07-08 00:42 UTC
Hey!

Not sure if you are still watching this repo but I'd love to have this yummy logo in my collection.
https://github.com/gilbarbara/logos
http://svgporn.com/

:+1:

**Comment by sindresorhus** [comment] 2015-07-08 02:16
I would love to too. Last time I tried exporting the logo as SVG I couldn't make it look right. Same issue now too.

Here's the Illustrator file if anyone wants to try: https://dl.dropboxusercontent.com/u/71884/monster.ai

The issue is that it loses some of its gradients. It might be possible to somehow simplify the layers, merge them, or something, but I'm far from an Illustrator expert.

**Comment by gilbarbara** [comment] 2015-07-08 04:11
Hey,

This is my first version, I had to make a few little changes since multiply don't really work with SVGs, but hey, it's working! http://kollectiv.org/files/tastejs-v1.svg

**Comment by gilbarbara** [comment] 2015-07-08 04:12
Actually, this is the one! http://kollectiv.org/files/tastejs-v2.svg

**Comment by sindresorhus** [comment] 2015-07-08 09:27
@gilbarbara Awesome! How did you do it? I want to learn.

**Comment by passy** [comment] 2015-07-08 10:11
That's awesome! Woah!

**Comment by arthurvr** [comment] 2015-07-08 10:15
Neat!

**Comment by gilbarbara** [comment] 2015-07-08 15:26
@sindresorhus It wasn't a straight forward process but..
- In Illustrator, select the layer on the Layers Panel and click on the panel menu and choose "Release to Layers (Sequence)". This will change the color interaction between the paths, multiply and shit.
- Save as SVG but AI will export some of the more complex layers as PNG too. (BAD)
- Then I opened the resulting SVG in Sketch and started to deal with the some paths and their respective multiplies/opacities. In this part I had to edit some paths, specially in the popsicle stick to make it more like the original.

bottomline:
AI shows the true opacities and color interactions but it is not so great at exporting.
Sketch has a better SVG conversion process but it still have some glitches.

Anyway, this is the latest version and I think it is satisfactory: http://kollectiv.org/files/tastejs-v4.svg
Is that ok?

**Comment by gilbarbara** [comment] 2015-07-08 16:00
oh well, I've added the popsicle shadow..
http://kollectiv.org/files/tastejs-v5.svg

**Comment by sindresorhus** [comment] 2015-07-09 22:50
@gilbarbara Looks good :D

Can you do a pull request on https://github.com/tastejs/media ? (so you get credit)

Some nitpicks:

- The light purple border around the eyes should have less opacity. See original.
- The dark parts on the ears should be darker.
- The shine on the head is too bright.
- The right side line that separates the arm from the body is almost gone and it's not that clear that it's an arm.

**Comment by gilbarbara** [comment] 2015-07-10 01:13
hey @sindresorhus 

I updated the ears, the head and the right arm but I couldn't see any difference between this and the original AI.
Please review it: https://github.com/tastejs/media/pull/1

:+1:

**Comment by arthurvr** [comment] 2015-07-20 11:54
Closing this as the PR landed :) Thanks again!

**Closed by arthurvr** 2015-07-20 11:54 UTC
